### PR TITLE
Added the functionality to toggle SideBar icons & MonacoEditor

### PR DESCRIPTION
**Pull request by dhrubajyotifounderofDSoft**

### CODE REVIEW

**Review by Dhrubajyo — APPROVED** [review]
Approved. Thankyou!

**Comment by Dhrubajyo** [comment]
I will be doing the updates in toggling feature of the Monaco Editor.

**Review by Dhrubajyo — APPROVED** [review]
Re-reviewed. Approved.

**Comment by dhrubajyotifounderofDSoft** [comment]
I have updated the [dependabot.yml](https://github.com/DSoftofficial/Tilder-web-app/pull/26/commits/5656ddd898f6910cb0985d632988d16fb34ec12e) with 2 main required packages.

**Pull request merged**
